################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
ASM_SRCS += \
../lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_app_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool1_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool2_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool3_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/cmpxchg8b_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/cmpxchg8b_with_explicit_ebx_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/df_test_app_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/df_test_tool1_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/df_test_tool2_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/df_test_tool3_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/df_test_tool4_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/df_test_tool5_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/ea_verifier_addr16_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/flag_ac_app_ia32_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/flag_ac_app_intel64_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/flag_spill_fill_app_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/flag_spill_fill_tool1_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/flags_at_analysis_app_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_app_ia32.asm \
../lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_app_intel64.asm \
../lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_df_app_ia32.asm \
../lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_df_ia32.asm \
../lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_ia32.asm \
../lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_intel64.asm \
../lib/pin2.14/source/tools/ToolUnitTests/inlined-stack-arg2_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/inlined-stack-arg2_win_intel64.asm \
../lib/pin2.14/source/tools/ToolUnitTests/mxcsr_ia32.asm \
../lib/pin2.14/source/tools/ToolUnitTests/mxcsr_intel64.asm \
../lib/pin2.14/source/tools/ToolUnitTests/pusha_popa_asm.asm \
../lib/pin2.14/source/tools/ToolUnitTests/reg_operands_test_app_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/seg_override_app1_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/segmented_ea_verifier_win1_ia32.asm \
../lib/pin2.14/source/tools/ToolUnitTests/segmented_ea_verifier_win1_intel64.asm \
../lib/pin2.14/source/tools/ToolUnitTests/set_xmm_scratches_ia32.asm \
../lib/pin2.14/source/tools/ToolUnitTests/set_xmm_scratches_intel64.asm \
../lib/pin2.14/source/tools/ToolUnitTests/spalign_asm_intel64_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/sse-ref_ia32.asm \
../lib/pin2.14/source/tools/ToolUnitTests/sse-ref_intel64.asm \
../lib/pin2.14/source/tools/ToolUnitTests/suspend-mxcsr-asm.asm \
../lib/pin2.14/source/tools/ToolUnitTests/swizzle_seg_app_ia32_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_ia32_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_intel64_win.asm \
../lib/pin2.14/source/tools/ToolUnitTests/test_inlined_consts_intel64.asm \
../lib/pin2.14/source/tools/ToolUnitTests/test_ip_access_app_intel64.asm \
../lib/pin2.14/source/tools/ToolUnitTests/test_lea_rip_intel64.asm 

CPP_SRCS += \
../lib/pin2.14/source/tools/ToolUnitTests/addr32_override_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/align_access.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool1.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool3.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/aoti_mutation_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/apc_monitor.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/app_inspects_internal_thread_win.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/args.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/args_err.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/args_lineno.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/attach.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/attach_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/baserel_in_probe_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/branch_target_addr.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp-flush.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp0.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp0i.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp1.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp10.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp10i.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp12.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp13.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp14.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp15.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp1i.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp3.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp4.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp5.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp6.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp7.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp8.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp9.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp_64bit_param_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp_nested_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callapp_perf_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callappfast10.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/callappstd10.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/change_syscall.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/check_env.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/check_env_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/check_fpstate.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/check_legal_callbacks.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/checkerrorfile.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/checkexecuting.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/checkinline.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/checkreps.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/claim_regs.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/clobber.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/code_cache_block_overflow1.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/code_cache_block_overflow2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/context.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/context_state_apis.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/control_init.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/create_rtn.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/create_rtn_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/data_in_code_win.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/datasym.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/debugservice_monitor.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/deepbind.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/df_test_tool1.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/df_test_tool2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/df_test_tool3.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/df_test_tool4.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/df_test_tool5.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/dlclose.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/dlclose_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/dynamic_secondary_dll.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/ea_verifier_addr16.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/ea_verifier_bt.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/earlymalloc.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/earlyout.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/elf_symbols.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/elf_symsize.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/emu_jumps.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/emu_stack.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/error_log.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/error_log_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/exceptionAddress_lin.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/exceptionAddress_lin_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/exception_context_monitor.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/exception_monitor.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/exception_monitor_for_iret_order.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/executeat_callback.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/executeat_lock.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/exports_only_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/farmain.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/fini.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/flag_ac_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/flag_ac_win_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/flag_spill_fill_tool1.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/flags_at_analysis_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/fp_args.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/fp_args_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/fp_context_set_const_context.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/fp_insert.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/fp_replace.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/funcarg_ep.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/funcarg_ep_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/funreplace_alert.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/guard_page.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/guard_page_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc1.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc3.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc4.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc5.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc_probed1.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/illegal_call_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/image_entry.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/image_load.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/incebx.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/indirect_call_branch_target_addr.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_df1.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_df3.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_df_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/inlinecall.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/inlined-stack-arg.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/inlined-stack-arg1.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/inlined-stack-arg2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/ins_check_fetcher.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/inscount2_fornoinline.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/insert_if_then_call.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/insert_if_then_call1.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/insert_if_then_call2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/insert_if_then_call_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/insertand.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/insfetch_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/int3del.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/internal_exception_handler.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/internal_exception_handler_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/internal_exception_handler_app_lin.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/internal_exception_handler_lin.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/intrin.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/jcx_addr16_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/jitmalloctrace.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/knob_duplicate_name.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/knob_writeonce.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/leave.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/line.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/main_dll.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/malmalloc.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/memalign.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/memory_displacement.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/memory_displacement_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/mmap.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/move_then_test.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/mt.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/mt_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/mt_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/mtflush.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/mtflushapp_unix.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/mtflushapp_win.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/multimem.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/nops.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/operandtool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/partialinline.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/passthru_context_xmm_regs_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/passthru_context_xmm_regs_callapp.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/passthru_context_xmm_regs_executeat.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/popea_verifier.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/posix_memalign.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/pusha_popa.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/raise_exception.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/raise_exception_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/realloc.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/rebase_dll_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_context_fp_st.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_const_context.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_fp_st.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_x87.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_xmm.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_ymm.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_context_x87.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_context_xmm.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_context_ymm.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_inst_gx.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_operands_test_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_ref_fp_st.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_ref_x87.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_ref_xmm.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_ref_ymm.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_value_fp_st.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_value_x87.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_value_xmm.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reg_value_ymm.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/repcmpsz_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/replace_free.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/replace_malloc_inst.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/replace_rtl_alloc_heap.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/reptool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/returnflags.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/returnflags_and_ref.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/returnreg.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/rewritememop.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/rewritememop1.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/rtn_insert_call1.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/rtn_insert_call2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/runnable.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/safecopy.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/safecopy_mxcsr.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/secname_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/secname_tool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/secure_scl_test.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/segmented_ea_verifier.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/set_fp_context_xmm_regs.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/set_fp_context_xmm_regs_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/set_xmm_scratches.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/short_name.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/smc_util.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/smcapp_bbl.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/smcapp_except.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/smcapp_ia32.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/smcapp_mt.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/socket_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/soload.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/soloadrange.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/sp_argument.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/spalign.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/spawntool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/sse-ref.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/sse-unaligned-class.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/sse-unaligned-class2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/sse.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/stackalign.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/static_secondary_dll.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/statica_locktest.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/str2flt.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/str2int.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/str2int64.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/strace_ia32.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/stracewin_ia32.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/stress_const_context.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/stress_const_context2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/stress_const_context_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/suspend-mxcsr.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/suspend_app_win.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/suspend_context_app_win.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/suspend_win.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/sw_interrupt.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/sw_interrupt_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/swizzle2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/swizzle3.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/swizzle5.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/swizzle_seg.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/swizzle_seg_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/syscall.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/syscall_std.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/syscall_std_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/teb.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/teb_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_iarg_partial_context.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_iarg_partial_context_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_app2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_mxcsr.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_mxcsr1.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_mxcsr_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_probe.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_probe_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_inlined_consts.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_ip_access.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_ip_access_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_lea_rip_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/test_sysenter_win.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/thenpredicated.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/thread_callback.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/thread_count.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/thread_count2.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/thread_pool.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/tool_full_path.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/tool_malloc.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/toolfetch_sub.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/undecorate.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/undecorateOperator_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/undecorate_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_callback.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_callback_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_code_on_reused_memory.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_cpp_exception.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_debug_service.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_divide_by_zero_exception.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_early_thread.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_early_thread_dll.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_exception_test.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_load_library.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_mxcsr_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_no_dependencies.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_queue_apc.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_syscallenum.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_thread_create_apc.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/win_tls_dll.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/winapp_exception_context.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/write_debugger_error.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/write_user_error.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/x87_regs_in_context.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/x87_regs_in_context_app.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/xmmapp.cpp \
../lib/pin2.14/source/tools/ToolUnitTests/xmmtest.cpp 

C_SRCS += \
../lib/pin2.14/source/tools/ToolUnitTests/addit.c \
../lib/pin2.14/source/tools/ToolUnitTests/align_access_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/aoti_mutation_target.c \
../lib/pin2.14/source/tools/ToolUnitTests/app_inspects_internal_thread_win_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/big_bss.c \
../lib/pin2.14/source/tools/ToolUnitTests/btc_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/callapp_64bit_param_app_1.c \
../lib/pin2.14/source/tools/ToolUnitTests/callapp_64bit_param_app_2.c \
../lib/pin2.14/source/tools/ToolUnitTests/callapp_nested_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/callapp_nested_app1.c \
../lib/pin2.14/source/tools/ToolUnitTests/callapp_perf_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/callapp_perf_app1.c \
../lib/pin2.14/source/tools/ToolUnitTests/cancel.c \
../lib/pin2.14/source/tools/ToolUnitTests/change_syscall_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/check_fpstate_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/cmovstest.c \
../lib/pin2.14/source/tools/ToolUnitTests/data_in_code_win_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/datasym_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/deepbind_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/deepbind_syscalls.c \
../lib/pin2.14/source/tools/ToolUnitTests/df_test_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/dltest.c \
../lib/pin2.14/source/tools/ToolUnitTests/dltest2.c \
../lib/pin2.14/source/tools/ToolUnitTests/doint.c \
../lib/pin2.14/source/tools/ToolUnitTests/dummy_dll.c \
../lib/pin2.14/source/tools/ToolUnitTests/execvp.c \
../lib/pin2.14/source/tools/ToolUnitTests/flag_ac_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/flag_ac_win_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/flag_spill_fill_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/flags_at_analysis_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/fp_replace_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/htab.c \
../lib/pin2.14/source/tools/ToolUnitTests/inner.c \
../lib/pin2.14/source/tools/ToolUnitTests/int3test.c \
../lib/pin2.14/source/tools/ToolUnitTests/iretmain_ia32.c \
../lib/pin2.14/source/tools/ToolUnitTests/iretmain_intel64.c \
../lib/pin2.14/source/tools/ToolUnitTests/iretmain_mic.c \
../lib/pin2.14/source/tools/ToolUnitTests/jcx_addr16_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/kthread.c \
../lib/pin2.14/source/tools/ToolUnitTests/little_malloc.c \
../lib/pin2.14/source/tools/ToolUnitTests/lpd.c \
../lib/pin2.14/source/tools/ToolUnitTests/one.c \
../lib/pin2.14/source/tools/ToolUnitTests/oneprog.c \
../lib/pin2.14/source/tools/ToolUnitTests/pipeapp.c \
../lib/pin2.14/source/tools/ToolUnitTests/pushtest.c \
../lib/pin2.14/source/tools/ToolUnitTests/rebase_dll.c \
../lib/pin2.14/source/tools/ToolUnitTests/reg_operands_test_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/repcmpsz.c \
../lib/pin2.14/source/tools/ToolUnitTests/reserve_memory.c \
../lib/pin2.14/source/tools/ToolUnitTests/seg_override_app1.c \
../lib/pin2.14/source/tools/ToolUnitTests/sigmask.c \
../lib/pin2.14/source/tools/ToolUnitTests/simple.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplebar.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplebar64.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefast10.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefoo.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefoo1.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefoo10.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefoo12.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefoo13.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefoo14.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefoo2.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefoo3.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefoo4.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefoo6.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefoo7.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefoo8.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplefoo9.c \
../lib/pin2.14/source/tools/ToolUnitTests/simplestd10.c \
../lib/pin2.14/source/tools/ToolUnitTests/sp_argument_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/spawntool_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/stringtest.c \
../lib/pin2.14/source/tools/ToolUnitTests/swizzlealloc.c \
../lib/pin2.14/source/tools/ToolUnitTests/symsize.c \
../lib/pin2.14/source/tools/ToolUnitTests/sys_memory_unix.c \
../lib/pin2.14/source/tools/ToolUnitTests/sys_memory_win.c \
../lib/pin2.14/source/tools/ToolUnitTests/thread.c \
../lib/pin2.14/source/tools/ToolUnitTests/thread_ea_addr16.c \
../lib/pin2.14/source/tools/ToolUnitTests/thread_segmented_ea.c \
../lib/pin2.14/source/tools/ToolUnitTests/thread_usestack.c \
../lib/pin2.14/source/tools/ToolUnitTests/thread_wait.c \
../lib/pin2.14/source/tools/ToolUnitTests/threadtestwin.c \
../lib/pin2.14/source/tools/ToolUnitTests/tool_fetch_app.c \
../lib/pin2.14/source/tools/ToolUnitTests/tstcmpxchg8b.c \
../lib/pin2.14/source/tools/ToolUnitTests/tstcmpxchg8b_with_explicit_ebx.c \
../lib/pin2.14/source/tools/ToolUnitTests/two.c \
../lib/pin2.14/source/tools/ToolUnitTests/waitpidbug.c 

OBJS += \
./lib/pin2.14/source/tools/ToolUnitTests/addit.o \
./lib/pin2.14/source/tools/ToolUnitTests/addr32_override_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/align_access.o \
./lib/pin2.14/source/tools/ToolUnitTests/align_access_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_app_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool1.o \
./lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool1_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool2.o \
./lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool2_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool3.o \
./lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool3_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/aoti_mutation_target.o \
./lib/pin2.14/source/tools/ToolUnitTests/aoti_mutation_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/apc_monitor.o \
./lib/pin2.14/source/tools/ToolUnitTests/app_inspects_internal_thread_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/app_inspects_internal_thread_win_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/args.o \
./lib/pin2.14/source/tools/ToolUnitTests/args_err.o \
./lib/pin2.14/source/tools/ToolUnitTests/args_lineno.o \
./lib/pin2.14/source/tools/ToolUnitTests/attach.o \
./lib/pin2.14/source/tools/ToolUnitTests/attach_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/baserel_in_probe_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/big_bss.o \
./lib/pin2.14/source/tools/ToolUnitTests/branch_target_addr.o \
./lib/pin2.14/source/tools/ToolUnitTests/btc_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp-flush.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp0.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp0i.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp1.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp10.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp10i.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp12.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp13.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp14.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp15.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp1i.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp2.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp3.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp4.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp5.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp6.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp7.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp8.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp9.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_64bit_param_app_1.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_64bit_param_app_2.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_64bit_param_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_nested_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_nested_app1.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_nested_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_perf_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_perf_app1.o \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_perf_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/callappfast10.o \
./lib/pin2.14/source/tools/ToolUnitTests/callappstd10.o \
./lib/pin2.14/source/tools/ToolUnitTests/cancel.o \
./lib/pin2.14/source/tools/ToolUnitTests/change_syscall.o \
./lib/pin2.14/source/tools/ToolUnitTests/change_syscall_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/check_env.o \
./lib/pin2.14/source/tools/ToolUnitTests/check_env_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/check_fpstate.o \
./lib/pin2.14/source/tools/ToolUnitTests/check_fpstate_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/check_legal_callbacks.o \
./lib/pin2.14/source/tools/ToolUnitTests/checkerrorfile.o \
./lib/pin2.14/source/tools/ToolUnitTests/checkexecuting.o \
./lib/pin2.14/source/tools/ToolUnitTests/checkinline.o \
./lib/pin2.14/source/tools/ToolUnitTests/checkreps.o \
./lib/pin2.14/source/tools/ToolUnitTests/claim_regs.o \
./lib/pin2.14/source/tools/ToolUnitTests/clobber.o \
./lib/pin2.14/source/tools/ToolUnitTests/cmovstest.o \
./lib/pin2.14/source/tools/ToolUnitTests/cmpxchg8b_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/cmpxchg8b_with_explicit_ebx_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/code_cache_block_overflow1.o \
./lib/pin2.14/source/tools/ToolUnitTests/code_cache_block_overflow2.o \
./lib/pin2.14/source/tools/ToolUnitTests/context.o \
./lib/pin2.14/source/tools/ToolUnitTests/context_state_apis.o \
./lib/pin2.14/source/tools/ToolUnitTests/control_init.o \
./lib/pin2.14/source/tools/ToolUnitTests/create_rtn.o \
./lib/pin2.14/source/tools/ToolUnitTests/create_rtn_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/data_in_code_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/data_in_code_win_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/datasym.o \
./lib/pin2.14/source/tools/ToolUnitTests/datasym_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/debugservice_monitor.o \
./lib/pin2.14/source/tools/ToolUnitTests/deepbind.o \
./lib/pin2.14/source/tools/ToolUnitTests/deepbind_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/deepbind_syscalls.o \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_app_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool1.o \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool1_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool2.o \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool2_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool3.o \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool3_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool4.o \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool4_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool5.o \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool5_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/dlclose.o \
./lib/pin2.14/source/tools/ToolUnitTests/dlclose_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/dltest.o \
./lib/pin2.14/source/tools/ToolUnitTests/dltest2.o \
./lib/pin2.14/source/tools/ToolUnitTests/doint.o \
./lib/pin2.14/source/tools/ToolUnitTests/dummy_dll.o \
./lib/pin2.14/source/tools/ToolUnitTests/dynamic_secondary_dll.o \
./lib/pin2.14/source/tools/ToolUnitTests/ea_verifier_addr16.o \
./lib/pin2.14/source/tools/ToolUnitTests/ea_verifier_addr16_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/ea_verifier_bt.o \
./lib/pin2.14/source/tools/ToolUnitTests/earlymalloc.o \
./lib/pin2.14/source/tools/ToolUnitTests/earlyout.o \
./lib/pin2.14/source/tools/ToolUnitTests/elf_symbols.o \
./lib/pin2.14/source/tools/ToolUnitTests/elf_symsize.o \
./lib/pin2.14/source/tools/ToolUnitTests/emu_jumps.o \
./lib/pin2.14/source/tools/ToolUnitTests/emu_stack.o \
./lib/pin2.14/source/tools/ToolUnitTests/error_log.o \
./lib/pin2.14/source/tools/ToolUnitTests/error_log_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/exceptionAddress_lin.o \
./lib/pin2.14/source/tools/ToolUnitTests/exceptionAddress_lin_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/exception_context_monitor.o \
./lib/pin2.14/source/tools/ToolUnitTests/exception_monitor.o \
./lib/pin2.14/source/tools/ToolUnitTests/exception_monitor_for_iret_order.o \
./lib/pin2.14/source/tools/ToolUnitTests/executeat_callback.o \
./lib/pin2.14/source/tools/ToolUnitTests/executeat_lock.o \
./lib/pin2.14/source/tools/ToolUnitTests/execvp.o \
./lib/pin2.14/source/tools/ToolUnitTests/exports_only_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/farmain.o \
./lib/pin2.14/source/tools/ToolUnitTests/fini.o \
./lib/pin2.14/source/tools/ToolUnitTests/flag_ac_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/flag_ac_app_ia32_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/flag_ac_app_intel64_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/flag_ac_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/flag_ac_win_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/flag_ac_win_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/flag_spill_fill_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/flag_spill_fill_app_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/flag_spill_fill_tool1.o \
./lib/pin2.14/source/tools/ToolUnitTests/flag_spill_fill_tool1_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/flags_at_analysis_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/flags_at_analysis_app_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/flags_at_analysis_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/fp_args.o \
./lib/pin2.14/source/tools/ToolUnitTests/fp_args_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/fp_context_set_const_context.o \
./lib/pin2.14/source/tools/ToolUnitTests/fp_insert.o \
./lib/pin2.14/source/tools/ToolUnitTests/fp_replace.o \
./lib/pin2.14/source/tools/ToolUnitTests/fp_replace_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/funcarg_ep.o \
./lib/pin2.14/source/tools/ToolUnitTests/funcarg_ep_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/funreplace_alert.o \
./lib/pin2.14/source/tools/ToolUnitTests/guard_page.o \
./lib/pin2.14/source/tools/ToolUnitTests/guard_page_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/htab.o \
./lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc1.o \
./lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc2.o \
./lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc3.o \
./lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc4.o \
./lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc5.o \
./lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc_probed1.o \
./lib/pin2.14/source/tools/ToolUnitTests/illegal_call_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/image_entry.o \
./lib/pin2.14/source/tools/ToolUnitTests/image_load.o \
./lib/pin2.14/source/tools/ToolUnitTests/incebx.o \
./lib/pin2.14/source/tools/ToolUnitTests/indirect_call_branch_target_addr.o \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test.o \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_app_ia32.o \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_app_intel64.o \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_df1.o \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_df3.o \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_df_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_df_app_ia32.o \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_df_ia32.o \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_ia32.o \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_intel64.o \
./lib/pin2.14/source/tools/ToolUnitTests/inlinecall.o \
./lib/pin2.14/source/tools/ToolUnitTests/inlined-stack-arg.o \
./lib/pin2.14/source/tools/ToolUnitTests/inlined-stack-arg1.o \
./lib/pin2.14/source/tools/ToolUnitTests/inlined-stack-arg2.o \
./lib/pin2.14/source/tools/ToolUnitTests/inlined-stack-arg2_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/inlined-stack-arg2_win_intel64.o \
./lib/pin2.14/source/tools/ToolUnitTests/inner.o \
./lib/pin2.14/source/tools/ToolUnitTests/ins_check_fetcher.o \
./lib/pin2.14/source/tools/ToolUnitTests/inscount2_fornoinline.o \
./lib/pin2.14/source/tools/ToolUnitTests/insert_if_then_call.o \
./lib/pin2.14/source/tools/ToolUnitTests/insert_if_then_call1.o \
./lib/pin2.14/source/tools/ToolUnitTests/insert_if_then_call2.o \
./lib/pin2.14/source/tools/ToolUnitTests/insert_if_then_call_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/insertand.o \
./lib/pin2.14/source/tools/ToolUnitTests/insfetch_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/int3del.o \
./lib/pin2.14/source/tools/ToolUnitTests/int3test.o \
./lib/pin2.14/source/tools/ToolUnitTests/internal_exception_handler.o \
./lib/pin2.14/source/tools/ToolUnitTests/internal_exception_handler_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/internal_exception_handler_app_lin.o \
./lib/pin2.14/source/tools/ToolUnitTests/internal_exception_handler_lin.o \
./lib/pin2.14/source/tools/ToolUnitTests/intrin.o \
./lib/pin2.14/source/tools/ToolUnitTests/iretmain_ia32.o \
./lib/pin2.14/source/tools/ToolUnitTests/iretmain_intel64.o \
./lib/pin2.14/source/tools/ToolUnitTests/iretmain_mic.o \
./lib/pin2.14/source/tools/ToolUnitTests/jcx_addr16_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/jcx_addr16_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/jitmalloctrace.o \
./lib/pin2.14/source/tools/ToolUnitTests/knob_duplicate_name.o \
./lib/pin2.14/source/tools/ToolUnitTests/knob_writeonce.o \
./lib/pin2.14/source/tools/ToolUnitTests/kthread.o \
./lib/pin2.14/source/tools/ToolUnitTests/leave.o \
./lib/pin2.14/source/tools/ToolUnitTests/line.o \
./lib/pin2.14/source/tools/ToolUnitTests/little_malloc.o \
./lib/pin2.14/source/tools/ToolUnitTests/lpd.o \
./lib/pin2.14/source/tools/ToolUnitTests/main_dll.o \
./lib/pin2.14/source/tools/ToolUnitTests/malmalloc.o \
./lib/pin2.14/source/tools/ToolUnitTests/memalign.o \
./lib/pin2.14/source/tools/ToolUnitTests/memory_displacement.o \
./lib/pin2.14/source/tools/ToolUnitTests/memory_displacement_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/mmap.o \
./lib/pin2.14/source/tools/ToolUnitTests/move_then_test.o \
./lib/pin2.14/source/tools/ToolUnitTests/mt.o \
./lib/pin2.14/source/tools/ToolUnitTests/mt_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/mt_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/mtflush.o \
./lib/pin2.14/source/tools/ToolUnitTests/mtflushapp_unix.o \
./lib/pin2.14/source/tools/ToolUnitTests/mtflushapp_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/multimem.o \
./lib/pin2.14/source/tools/ToolUnitTests/mxcsr_ia32.o \
./lib/pin2.14/source/tools/ToolUnitTests/mxcsr_intel64.o \
./lib/pin2.14/source/tools/ToolUnitTests/nops.o \
./lib/pin2.14/source/tools/ToolUnitTests/one.o \
./lib/pin2.14/source/tools/ToolUnitTests/oneprog.o \
./lib/pin2.14/source/tools/ToolUnitTests/operandtool.o \
./lib/pin2.14/source/tools/ToolUnitTests/partialinline.o \
./lib/pin2.14/source/tools/ToolUnitTests/passthru_context_xmm_regs_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/passthru_context_xmm_regs_callapp.o \
./lib/pin2.14/source/tools/ToolUnitTests/passthru_context_xmm_regs_executeat.o \
./lib/pin2.14/source/tools/ToolUnitTests/pipeapp.o \
./lib/pin2.14/source/tools/ToolUnitTests/popea_verifier.o \
./lib/pin2.14/source/tools/ToolUnitTests/posix_memalign.o \
./lib/pin2.14/source/tools/ToolUnitTests/pusha_popa.o \
./lib/pin2.14/source/tools/ToolUnitTests/pusha_popa_asm.o \
./lib/pin2.14/source/tools/ToolUnitTests/pushtest.o \
./lib/pin2.14/source/tools/ToolUnitTests/raise_exception.o \
./lib/pin2.14/source/tools/ToolUnitTests/raise_exception_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/realloc.o \
./lib/pin2.14/source/tools/ToolUnitTests/rebase_dll.o \
./lib/pin2.14/source/tools/ToolUnitTests/rebase_dll_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_fp_st.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_const_context.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_fp_st.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_x87.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_xmm.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_ymm.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_x87.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_xmm.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_ymm.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_inst_gx.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_operands_test_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_operands_test_app_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_operands_test_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_ref_fp_st.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_ref_x87.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_ref_xmm.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_ref_ymm.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_value_fp_st.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_value_x87.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_value_xmm.o \
./lib/pin2.14/source/tools/ToolUnitTests/reg_value_ymm.o \
./lib/pin2.14/source/tools/ToolUnitTests/repcmpsz.o \
./lib/pin2.14/source/tools/ToolUnitTests/repcmpsz_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/replace_free.o \
./lib/pin2.14/source/tools/ToolUnitTests/replace_malloc_inst.o \
./lib/pin2.14/source/tools/ToolUnitTests/replace_rtl_alloc_heap.o \
./lib/pin2.14/source/tools/ToolUnitTests/reptool.o \
./lib/pin2.14/source/tools/ToolUnitTests/reserve_memory.o \
./lib/pin2.14/source/tools/ToolUnitTests/returnflags.o \
./lib/pin2.14/source/tools/ToolUnitTests/returnflags_and_ref.o \
./lib/pin2.14/source/tools/ToolUnitTests/returnreg.o \
./lib/pin2.14/source/tools/ToolUnitTests/rewritememop.o \
./lib/pin2.14/source/tools/ToolUnitTests/rewritememop1.o \
./lib/pin2.14/source/tools/ToolUnitTests/rtn_insert_call1.o \
./lib/pin2.14/source/tools/ToolUnitTests/rtn_insert_call2.o \
./lib/pin2.14/source/tools/ToolUnitTests/runnable.o \
./lib/pin2.14/source/tools/ToolUnitTests/safecopy.o \
./lib/pin2.14/source/tools/ToolUnitTests/safecopy_mxcsr.o \
./lib/pin2.14/source/tools/ToolUnitTests/secname_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/secname_tool.o \
./lib/pin2.14/source/tools/ToolUnitTests/secure_scl_test.o \
./lib/pin2.14/source/tools/ToolUnitTests/seg_override_app1.o \
./lib/pin2.14/source/tools/ToolUnitTests/seg_override_app1_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/segmented_ea_verifier.o \
./lib/pin2.14/source/tools/ToolUnitTests/segmented_ea_verifier_win1_ia32.o \
./lib/pin2.14/source/tools/ToolUnitTests/segmented_ea_verifier_win1_intel64.o \
./lib/pin2.14/source/tools/ToolUnitTests/set_fp_context_xmm_regs.o \
./lib/pin2.14/source/tools/ToolUnitTests/set_fp_context_xmm_regs_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/set_xmm_scratches.o \
./lib/pin2.14/source/tools/ToolUnitTests/set_xmm_scratches_ia32.o \
./lib/pin2.14/source/tools/ToolUnitTests/set_xmm_scratches_intel64.o \
./lib/pin2.14/source/tools/ToolUnitTests/short_name.o \
./lib/pin2.14/source/tools/ToolUnitTests/sigmask.o \
./lib/pin2.14/source/tools/ToolUnitTests/simple.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplebar.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplebar64.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefast10.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo1.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo10.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo12.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo13.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo14.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo2.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo3.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo4.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo6.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo7.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo8.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo9.o \
./lib/pin2.14/source/tools/ToolUnitTests/simplestd10.o \
./lib/pin2.14/source/tools/ToolUnitTests/smc_util.o \
./lib/pin2.14/source/tools/ToolUnitTests/smcapp_bbl.o \
./lib/pin2.14/source/tools/ToolUnitTests/smcapp_except.o \
./lib/pin2.14/source/tools/ToolUnitTests/smcapp_ia32.o \
./lib/pin2.14/source/tools/ToolUnitTests/smcapp_mt.o \
./lib/pin2.14/source/tools/ToolUnitTests/socket_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/soload.o \
./lib/pin2.14/source/tools/ToolUnitTests/soloadrange.o \
./lib/pin2.14/source/tools/ToolUnitTests/sp_argument.o \
./lib/pin2.14/source/tools/ToolUnitTests/sp_argument_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/spalign.o \
./lib/pin2.14/source/tools/ToolUnitTests/spalign_asm_intel64_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/spawntool.o \
./lib/pin2.14/source/tools/ToolUnitTests/spawntool_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/sse-ref.o \
./lib/pin2.14/source/tools/ToolUnitTests/sse-ref_ia32.o \
./lib/pin2.14/source/tools/ToolUnitTests/sse-ref_intel64.o \
./lib/pin2.14/source/tools/ToolUnitTests/sse-unaligned-class.o \
./lib/pin2.14/source/tools/ToolUnitTests/sse-unaligned-class2.o \
./lib/pin2.14/source/tools/ToolUnitTests/sse.o \
./lib/pin2.14/source/tools/ToolUnitTests/stackalign.o \
./lib/pin2.14/source/tools/ToolUnitTests/static_secondary_dll.o \
./lib/pin2.14/source/tools/ToolUnitTests/statica_locktest.o \
./lib/pin2.14/source/tools/ToolUnitTests/str2flt.o \
./lib/pin2.14/source/tools/ToolUnitTests/str2int.o \
./lib/pin2.14/source/tools/ToolUnitTests/str2int64.o \
./lib/pin2.14/source/tools/ToolUnitTests/strace_ia32.o \
./lib/pin2.14/source/tools/ToolUnitTests/stracewin_ia32.o \
./lib/pin2.14/source/tools/ToolUnitTests/stress_const_context.o \
./lib/pin2.14/source/tools/ToolUnitTests/stress_const_context2.o \
./lib/pin2.14/source/tools/ToolUnitTests/stress_const_context_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/stringtest.o \
./lib/pin2.14/source/tools/ToolUnitTests/suspend-mxcsr-asm.o \
./lib/pin2.14/source/tools/ToolUnitTests/suspend-mxcsr.o \
./lib/pin2.14/source/tools/ToolUnitTests/suspend_app_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/suspend_context_app_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/suspend_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/sw_interrupt.o \
./lib/pin2.14/source/tools/ToolUnitTests/sw_interrupt_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/swizzle2.o \
./lib/pin2.14/source/tools/ToolUnitTests/swizzle3.o \
./lib/pin2.14/source/tools/ToolUnitTests/swizzle5.o \
./lib/pin2.14/source/tools/ToolUnitTests/swizzle_seg.o \
./lib/pin2.14/source/tools/ToolUnitTests/swizzle_seg_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/swizzle_seg_app_ia32_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/swizzlealloc.o \
./lib/pin2.14/source/tools/ToolUnitTests/symsize.o \
./lib/pin2.14/source/tools/ToolUnitTests/sys_memory_unix.o \
./lib/pin2.14/source/tools/ToolUnitTests/sys_memory_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/syscall.o \
./lib/pin2.14/source/tools/ToolUnitTests/syscall_std.o \
./lib/pin2.14/source/tools/ToolUnitTests/syscall_std_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/teb.o \
./lib/pin2.14/source/tools/ToolUnitTests/teb_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_partial_context.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_partial_context_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve2.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_app2.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_ia32_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_intel64_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_mxcsr.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_mxcsr1.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_mxcsr_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_probe.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_probe_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_inlined_consts.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_inlined_consts_intel64.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_ip_access.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_ip_access_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_ip_access_app_intel64.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_lea_rip_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_lea_rip_intel64.o \
./lib/pin2.14/source/tools/ToolUnitTests/test_sysenter_win.o \
./lib/pin2.14/source/tools/ToolUnitTests/thenpredicated.o \
./lib/pin2.14/source/tools/ToolUnitTests/thread.o \
./lib/pin2.14/source/tools/ToolUnitTests/thread_callback.o \
./lib/pin2.14/source/tools/ToolUnitTests/thread_count.o \
./lib/pin2.14/source/tools/ToolUnitTests/thread_count2.o \
./lib/pin2.14/source/tools/ToolUnitTests/thread_ea_addr16.o \
./lib/pin2.14/source/tools/ToolUnitTests/thread_pool.o \
./lib/pin2.14/source/tools/ToolUnitTests/thread_segmented_ea.o \
./lib/pin2.14/source/tools/ToolUnitTests/thread_usestack.o \
./lib/pin2.14/source/tools/ToolUnitTests/thread_wait.o \
./lib/pin2.14/source/tools/ToolUnitTests/threadtestwin.o \
./lib/pin2.14/source/tools/ToolUnitTests/tool_fetch_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/tool_full_path.o \
./lib/pin2.14/source/tools/ToolUnitTests/tool_malloc.o \
./lib/pin2.14/source/tools/ToolUnitTests/toolfetch_sub.o \
./lib/pin2.14/source/tools/ToolUnitTests/tstcmpxchg8b.o \
./lib/pin2.14/source/tools/ToolUnitTests/tstcmpxchg8b_with_explicit_ebx.o \
./lib/pin2.14/source/tools/ToolUnitTests/two.o \
./lib/pin2.14/source/tools/ToolUnitTests/undecorate.o \
./lib/pin2.14/source/tools/ToolUnitTests/undecorateOperator_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/undecorate_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/waitpidbug.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_callback.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_callback_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_code_on_reused_memory.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_cpp_exception.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_debug_service.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_divide_by_zero_exception.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_early_thread.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_early_thread_dll.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_exception_test.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_load_library.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_mxcsr_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_no_dependencies.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_queue_apc.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_syscallenum.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_thread_create_apc.o \
./lib/pin2.14/source/tools/ToolUnitTests/win_tls_dll.o \
./lib/pin2.14/source/tools/ToolUnitTests/winapp_exception_context.o \
./lib/pin2.14/source/tools/ToolUnitTests/write_debugger_error.o \
./lib/pin2.14/source/tools/ToolUnitTests/write_user_error.o \
./lib/pin2.14/source/tools/ToolUnitTests/x87_regs_in_context.o \
./lib/pin2.14/source/tools/ToolUnitTests/x87_regs_in_context_app.o \
./lib/pin2.14/source/tools/ToolUnitTests/xmmapp.o \
./lib/pin2.14/source/tools/ToolUnitTests/xmmtest.o 

CPP_DEPS += \
./lib/pin2.14/source/tools/ToolUnitTests/addr32_override_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/align_access.d \
./lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool1.d \
./lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool2.d \
./lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_tool3.d \
./lib/pin2.14/source/tools/ToolUnitTests/aoti_mutation_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/apc_monitor.d \
./lib/pin2.14/source/tools/ToolUnitTests/app_inspects_internal_thread_win.d \
./lib/pin2.14/source/tools/ToolUnitTests/args.d \
./lib/pin2.14/source/tools/ToolUnitTests/args_err.d \
./lib/pin2.14/source/tools/ToolUnitTests/args_lineno.d \
./lib/pin2.14/source/tools/ToolUnitTests/attach.d \
./lib/pin2.14/source/tools/ToolUnitTests/attach_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/baserel_in_probe_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/branch_target_addr.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp-flush.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp0.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp0i.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp1.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp10.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp10i.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp12.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp13.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp14.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp15.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp1i.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp2.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp3.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp4.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp5.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp6.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp7.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp8.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp9.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_64bit_param_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_nested_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_perf_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/callappfast10.d \
./lib/pin2.14/source/tools/ToolUnitTests/callappstd10.d \
./lib/pin2.14/source/tools/ToolUnitTests/change_syscall.d \
./lib/pin2.14/source/tools/ToolUnitTests/check_env.d \
./lib/pin2.14/source/tools/ToolUnitTests/check_env_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/check_fpstate.d \
./lib/pin2.14/source/tools/ToolUnitTests/check_legal_callbacks.d \
./lib/pin2.14/source/tools/ToolUnitTests/checkerrorfile.d \
./lib/pin2.14/source/tools/ToolUnitTests/checkexecuting.d \
./lib/pin2.14/source/tools/ToolUnitTests/checkinline.d \
./lib/pin2.14/source/tools/ToolUnitTests/checkreps.d \
./lib/pin2.14/source/tools/ToolUnitTests/claim_regs.d \
./lib/pin2.14/source/tools/ToolUnitTests/clobber.d \
./lib/pin2.14/source/tools/ToolUnitTests/code_cache_block_overflow1.d \
./lib/pin2.14/source/tools/ToolUnitTests/code_cache_block_overflow2.d \
./lib/pin2.14/source/tools/ToolUnitTests/context.d \
./lib/pin2.14/source/tools/ToolUnitTests/context_state_apis.d \
./lib/pin2.14/source/tools/ToolUnitTests/control_init.d \
./lib/pin2.14/source/tools/ToolUnitTests/create_rtn.d \
./lib/pin2.14/source/tools/ToolUnitTests/create_rtn_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/data_in_code_win.d \
./lib/pin2.14/source/tools/ToolUnitTests/datasym.d \
./lib/pin2.14/source/tools/ToolUnitTests/debugservice_monitor.d \
./lib/pin2.14/source/tools/ToolUnitTests/deepbind.d \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool1.d \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool2.d \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool3.d \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool4.d \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_tool5.d \
./lib/pin2.14/source/tools/ToolUnitTests/dlclose.d \
./lib/pin2.14/source/tools/ToolUnitTests/dlclose_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/dynamic_secondary_dll.d \
./lib/pin2.14/source/tools/ToolUnitTests/ea_verifier_addr16.d \
./lib/pin2.14/source/tools/ToolUnitTests/ea_verifier_bt.d \
./lib/pin2.14/source/tools/ToolUnitTests/earlymalloc.d \
./lib/pin2.14/source/tools/ToolUnitTests/earlyout.d \
./lib/pin2.14/source/tools/ToolUnitTests/elf_symbols.d \
./lib/pin2.14/source/tools/ToolUnitTests/elf_symsize.d \
./lib/pin2.14/source/tools/ToolUnitTests/emu_jumps.d \
./lib/pin2.14/source/tools/ToolUnitTests/emu_stack.d \
./lib/pin2.14/source/tools/ToolUnitTests/error_log.d \
./lib/pin2.14/source/tools/ToolUnitTests/error_log_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/exceptionAddress_lin.d \
./lib/pin2.14/source/tools/ToolUnitTests/exceptionAddress_lin_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/exception_context_monitor.d \
./lib/pin2.14/source/tools/ToolUnitTests/exception_monitor.d \
./lib/pin2.14/source/tools/ToolUnitTests/exception_monitor_for_iret_order.d \
./lib/pin2.14/source/tools/ToolUnitTests/executeat_callback.d \
./lib/pin2.14/source/tools/ToolUnitTests/executeat_lock.d \
./lib/pin2.14/source/tools/ToolUnitTests/exports_only_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/farmain.d \
./lib/pin2.14/source/tools/ToolUnitTests/fini.d \
./lib/pin2.14/source/tools/ToolUnitTests/flag_ac_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/flag_ac_win_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/flag_spill_fill_tool1.d \
./lib/pin2.14/source/tools/ToolUnitTests/flags_at_analysis_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/fp_args.d \
./lib/pin2.14/source/tools/ToolUnitTests/fp_args_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/fp_context_set_const_context.d \
./lib/pin2.14/source/tools/ToolUnitTests/fp_insert.d \
./lib/pin2.14/source/tools/ToolUnitTests/fp_replace.d \
./lib/pin2.14/source/tools/ToolUnitTests/funcarg_ep.d \
./lib/pin2.14/source/tools/ToolUnitTests/funcarg_ep_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/funreplace_alert.d \
./lib/pin2.14/source/tools/ToolUnitTests/guard_page.d \
./lib/pin2.14/source/tools/ToolUnitTests/guard_page_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc1.d \
./lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc2.d \
./lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc3.d \
./lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc4.d \
./lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc5.d \
./lib/pin2.14/source/tools/ToolUnitTests/iarg_tsc_probed1.d \
./lib/pin2.14/source/tools/ToolUnitTests/illegal_call_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/image_entry.d \
./lib/pin2.14/source/tools/ToolUnitTests/image_load.d \
./lib/pin2.14/source/tools/ToolUnitTests/incebx.d \
./lib/pin2.14/source/tools/ToolUnitTests/indirect_call_branch_target_addr.d \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test.d \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_df1.d \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_df3.d \
./lib/pin2.14/source/tools/ToolUnitTests/inline_opt_test_df_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/inlinecall.d \
./lib/pin2.14/source/tools/ToolUnitTests/inlined-stack-arg.d \
./lib/pin2.14/source/tools/ToolUnitTests/inlined-stack-arg1.d \
./lib/pin2.14/source/tools/ToolUnitTests/inlined-stack-arg2.d \
./lib/pin2.14/source/tools/ToolUnitTests/ins_check_fetcher.d \
./lib/pin2.14/source/tools/ToolUnitTests/inscount2_fornoinline.d \
./lib/pin2.14/source/tools/ToolUnitTests/insert_if_then_call.d \
./lib/pin2.14/source/tools/ToolUnitTests/insert_if_then_call1.d \
./lib/pin2.14/source/tools/ToolUnitTests/insert_if_then_call2.d \
./lib/pin2.14/source/tools/ToolUnitTests/insert_if_then_call_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/insertand.d \
./lib/pin2.14/source/tools/ToolUnitTests/insfetch_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/int3del.d \
./lib/pin2.14/source/tools/ToolUnitTests/internal_exception_handler.d \
./lib/pin2.14/source/tools/ToolUnitTests/internal_exception_handler_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/internal_exception_handler_app_lin.d \
./lib/pin2.14/source/tools/ToolUnitTests/internal_exception_handler_lin.d \
./lib/pin2.14/source/tools/ToolUnitTests/intrin.d \
./lib/pin2.14/source/tools/ToolUnitTests/jcx_addr16_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/jitmalloctrace.d \
./lib/pin2.14/source/tools/ToolUnitTests/knob_duplicate_name.d \
./lib/pin2.14/source/tools/ToolUnitTests/knob_writeonce.d \
./lib/pin2.14/source/tools/ToolUnitTests/leave.d \
./lib/pin2.14/source/tools/ToolUnitTests/line.d \
./lib/pin2.14/source/tools/ToolUnitTests/main_dll.d \
./lib/pin2.14/source/tools/ToolUnitTests/malmalloc.d \
./lib/pin2.14/source/tools/ToolUnitTests/memalign.d \
./lib/pin2.14/source/tools/ToolUnitTests/memory_displacement.d \
./lib/pin2.14/source/tools/ToolUnitTests/memory_displacement_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/mmap.d \
./lib/pin2.14/source/tools/ToolUnitTests/move_then_test.d \
./lib/pin2.14/source/tools/ToolUnitTests/mt.d \
./lib/pin2.14/source/tools/ToolUnitTests/mt_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/mt_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/mtflush.d \
./lib/pin2.14/source/tools/ToolUnitTests/mtflushapp_unix.d \
./lib/pin2.14/source/tools/ToolUnitTests/mtflushapp_win.d \
./lib/pin2.14/source/tools/ToolUnitTests/multimem.d \
./lib/pin2.14/source/tools/ToolUnitTests/nops.d \
./lib/pin2.14/source/tools/ToolUnitTests/operandtool.d \
./lib/pin2.14/source/tools/ToolUnitTests/partialinline.d \
./lib/pin2.14/source/tools/ToolUnitTests/passthru_context_xmm_regs_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/passthru_context_xmm_regs_callapp.d \
./lib/pin2.14/source/tools/ToolUnitTests/passthru_context_xmm_regs_executeat.d \
./lib/pin2.14/source/tools/ToolUnitTests/popea_verifier.d \
./lib/pin2.14/source/tools/ToolUnitTests/posix_memalign.d \
./lib/pin2.14/source/tools/ToolUnitTests/pusha_popa.d \
./lib/pin2.14/source/tools/ToolUnitTests/raise_exception.d \
./lib/pin2.14/source/tools/ToolUnitTests/raise_exception_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/realloc.d \
./lib/pin2.14/source/tools/ToolUnitTests/rebase_dll_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_fp_st.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_const_context.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_fp_st.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_x87.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_xmm.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_set_ymm.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_x87.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_xmm.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_context_ymm.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_inst_gx.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_operands_test_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_ref_fp_st.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_ref_x87.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_ref_xmm.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_ref_ymm.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_value_fp_st.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_value_x87.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_value_xmm.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_value_ymm.d \
./lib/pin2.14/source/tools/ToolUnitTests/repcmpsz_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/replace_free.d \
./lib/pin2.14/source/tools/ToolUnitTests/replace_malloc_inst.d \
./lib/pin2.14/source/tools/ToolUnitTests/replace_rtl_alloc_heap.d \
./lib/pin2.14/source/tools/ToolUnitTests/reptool.d \
./lib/pin2.14/source/tools/ToolUnitTests/returnflags.d \
./lib/pin2.14/source/tools/ToolUnitTests/returnflags_and_ref.d \
./lib/pin2.14/source/tools/ToolUnitTests/returnreg.d \
./lib/pin2.14/source/tools/ToolUnitTests/rewritememop.d \
./lib/pin2.14/source/tools/ToolUnitTests/rewritememop1.d \
./lib/pin2.14/source/tools/ToolUnitTests/rtn_insert_call1.d \
./lib/pin2.14/source/tools/ToolUnitTests/rtn_insert_call2.d \
./lib/pin2.14/source/tools/ToolUnitTests/runnable.d \
./lib/pin2.14/source/tools/ToolUnitTests/safecopy.d \
./lib/pin2.14/source/tools/ToolUnitTests/safecopy_mxcsr.d \
./lib/pin2.14/source/tools/ToolUnitTests/secname_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/secname_tool.d \
./lib/pin2.14/source/tools/ToolUnitTests/secure_scl_test.d \
./lib/pin2.14/source/tools/ToolUnitTests/segmented_ea_verifier.d \
./lib/pin2.14/source/tools/ToolUnitTests/set_fp_context_xmm_regs.d \
./lib/pin2.14/source/tools/ToolUnitTests/set_fp_context_xmm_regs_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/set_xmm_scratches.d \
./lib/pin2.14/source/tools/ToolUnitTests/short_name.d \
./lib/pin2.14/source/tools/ToolUnitTests/smc_util.d \
./lib/pin2.14/source/tools/ToolUnitTests/smcapp_bbl.d \
./lib/pin2.14/source/tools/ToolUnitTests/smcapp_except.d \
./lib/pin2.14/source/tools/ToolUnitTests/smcapp_ia32.d \
./lib/pin2.14/source/tools/ToolUnitTests/smcapp_mt.d \
./lib/pin2.14/source/tools/ToolUnitTests/socket_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/soload.d \
./lib/pin2.14/source/tools/ToolUnitTests/soloadrange.d \
./lib/pin2.14/source/tools/ToolUnitTests/sp_argument.d \
./lib/pin2.14/source/tools/ToolUnitTests/spalign.d \
./lib/pin2.14/source/tools/ToolUnitTests/spawntool.d \
./lib/pin2.14/source/tools/ToolUnitTests/sse-ref.d \
./lib/pin2.14/source/tools/ToolUnitTests/sse-unaligned-class.d \
./lib/pin2.14/source/tools/ToolUnitTests/sse-unaligned-class2.d \
./lib/pin2.14/source/tools/ToolUnitTests/sse.d \
./lib/pin2.14/source/tools/ToolUnitTests/stackalign.d \
./lib/pin2.14/source/tools/ToolUnitTests/static_secondary_dll.d \
./lib/pin2.14/source/tools/ToolUnitTests/statica_locktest.d \
./lib/pin2.14/source/tools/ToolUnitTests/str2flt.d \
./lib/pin2.14/source/tools/ToolUnitTests/str2int.d \
./lib/pin2.14/source/tools/ToolUnitTests/str2int64.d \
./lib/pin2.14/source/tools/ToolUnitTests/strace_ia32.d \
./lib/pin2.14/source/tools/ToolUnitTests/stracewin_ia32.d \
./lib/pin2.14/source/tools/ToolUnitTests/stress_const_context.d \
./lib/pin2.14/source/tools/ToolUnitTests/stress_const_context2.d \
./lib/pin2.14/source/tools/ToolUnitTests/stress_const_context_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/suspend-mxcsr.d \
./lib/pin2.14/source/tools/ToolUnitTests/suspend_app_win.d \
./lib/pin2.14/source/tools/ToolUnitTests/suspend_context_app_win.d \
./lib/pin2.14/source/tools/ToolUnitTests/suspend_win.d \
./lib/pin2.14/source/tools/ToolUnitTests/sw_interrupt.d \
./lib/pin2.14/source/tools/ToolUnitTests/sw_interrupt_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/swizzle2.d \
./lib/pin2.14/source/tools/ToolUnitTests/swizzle3.d \
./lib/pin2.14/source/tools/ToolUnitTests/swizzle5.d \
./lib/pin2.14/source/tools/ToolUnitTests/swizzle_seg.d \
./lib/pin2.14/source/tools/ToolUnitTests/swizzle_seg_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/syscall.d \
./lib/pin2.14/source/tools/ToolUnitTests/syscall_std.d \
./lib/pin2.14/source/tools/ToolUnitTests/syscall_std_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/teb.d \
./lib/pin2.14/source/tools/ToolUnitTests/teb_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_partial_context.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_partial_context_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve2.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_app2.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_mxcsr.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_mxcsr1.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_mxcsr_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_probe.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_iarg_preserve_probe_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_inlined_consts.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_ip_access.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_ip_access_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_lea_rip_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/test_sysenter_win.d \
./lib/pin2.14/source/tools/ToolUnitTests/thenpredicated.d \
./lib/pin2.14/source/tools/ToolUnitTests/thread_callback.d \
./lib/pin2.14/source/tools/ToolUnitTests/thread_count.d \
./lib/pin2.14/source/tools/ToolUnitTests/thread_count2.d \
./lib/pin2.14/source/tools/ToolUnitTests/thread_pool.d \
./lib/pin2.14/source/tools/ToolUnitTests/tool_full_path.d \
./lib/pin2.14/source/tools/ToolUnitTests/tool_malloc.d \
./lib/pin2.14/source/tools/ToolUnitTests/toolfetch_sub.d \
./lib/pin2.14/source/tools/ToolUnitTests/undecorate.d \
./lib/pin2.14/source/tools/ToolUnitTests/undecorateOperator_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/undecorate_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_callback.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_callback_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_code_on_reused_memory.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_cpp_exception.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_debug_service.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_divide_by_zero_exception.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_early_thread.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_early_thread_dll.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_exception_test.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_load_library.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_mxcsr_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_no_dependencies.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_queue_apc.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_syscallenum.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_thread_create_apc.d \
./lib/pin2.14/source/tools/ToolUnitTests/win_tls_dll.d \
./lib/pin2.14/source/tools/ToolUnitTests/winapp_exception_context.d \
./lib/pin2.14/source/tools/ToolUnitTests/write_debugger_error.d \
./lib/pin2.14/source/tools/ToolUnitTests/write_user_error.d \
./lib/pin2.14/source/tools/ToolUnitTests/x87_regs_in_context.d \
./lib/pin2.14/source/tools/ToolUnitTests/x87_regs_in_context_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/xmmapp.d \
./lib/pin2.14/source/tools/ToolUnitTests/xmmtest.d 

C_DEPS += \
./lib/pin2.14/source/tools/ToolUnitTests/addit.d \
./lib/pin2.14/source/tools/ToolUnitTests/align_access_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/analysis_flag_overwrite_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/aoti_mutation_target.d \
./lib/pin2.14/source/tools/ToolUnitTests/app_inspects_internal_thread_win_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/big_bss.d \
./lib/pin2.14/source/tools/ToolUnitTests/btc_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_64bit_param_app_1.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_64bit_param_app_2.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_nested_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_nested_app1.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_perf_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/callapp_perf_app1.d \
./lib/pin2.14/source/tools/ToolUnitTests/cancel.d \
./lib/pin2.14/source/tools/ToolUnitTests/change_syscall_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/check_fpstate_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/cmovstest.d \
./lib/pin2.14/source/tools/ToolUnitTests/data_in_code_win_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/datasym_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/deepbind_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/deepbind_syscalls.d \
./lib/pin2.14/source/tools/ToolUnitTests/df_test_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/dltest.d \
./lib/pin2.14/source/tools/ToolUnitTests/dltest2.d \
./lib/pin2.14/source/tools/ToolUnitTests/doint.d \
./lib/pin2.14/source/tools/ToolUnitTests/dummy_dll.d \
./lib/pin2.14/source/tools/ToolUnitTests/execvp.d \
./lib/pin2.14/source/tools/ToolUnitTests/flag_ac_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/flag_ac_win_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/flag_spill_fill_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/flags_at_analysis_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/fp_replace_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/htab.d \
./lib/pin2.14/source/tools/ToolUnitTests/inner.d \
./lib/pin2.14/source/tools/ToolUnitTests/int3test.d \
./lib/pin2.14/source/tools/ToolUnitTests/iretmain_ia32.d \
./lib/pin2.14/source/tools/ToolUnitTests/iretmain_intel64.d \
./lib/pin2.14/source/tools/ToolUnitTests/iretmain_mic.d \
./lib/pin2.14/source/tools/ToolUnitTests/jcx_addr16_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/kthread.d \
./lib/pin2.14/source/tools/ToolUnitTests/little_malloc.d \
./lib/pin2.14/source/tools/ToolUnitTests/lpd.d \
./lib/pin2.14/source/tools/ToolUnitTests/one.d \
./lib/pin2.14/source/tools/ToolUnitTests/oneprog.d \
./lib/pin2.14/source/tools/ToolUnitTests/pipeapp.d \
./lib/pin2.14/source/tools/ToolUnitTests/pushtest.d \
./lib/pin2.14/source/tools/ToolUnitTests/rebase_dll.d \
./lib/pin2.14/source/tools/ToolUnitTests/reg_operands_test_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/repcmpsz.d \
./lib/pin2.14/source/tools/ToolUnitTests/reserve_memory.d \
./lib/pin2.14/source/tools/ToolUnitTests/seg_override_app1.d \
./lib/pin2.14/source/tools/ToolUnitTests/sigmask.d \
./lib/pin2.14/source/tools/ToolUnitTests/simple.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplebar.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplebar64.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefast10.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo1.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo10.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo12.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo13.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo14.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo2.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo3.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo4.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo6.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo7.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo8.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplefoo9.d \
./lib/pin2.14/source/tools/ToolUnitTests/simplestd10.d \
./lib/pin2.14/source/tools/ToolUnitTests/sp_argument_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/spawntool_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/stringtest.d \
./lib/pin2.14/source/tools/ToolUnitTests/swizzlealloc.d \
./lib/pin2.14/source/tools/ToolUnitTests/symsize.d \
./lib/pin2.14/source/tools/ToolUnitTests/sys_memory_unix.d \
./lib/pin2.14/source/tools/ToolUnitTests/sys_memory_win.d \
./lib/pin2.14/source/tools/ToolUnitTests/thread.d \
./lib/pin2.14/source/tools/ToolUnitTests/thread_ea_addr16.d \
./lib/pin2.14/source/tools/ToolUnitTests/thread_segmented_ea.d \
./lib/pin2.14/source/tools/ToolUnitTests/thread_usestack.d \
./lib/pin2.14/source/tools/ToolUnitTests/thread_wait.d \
./lib/pin2.14/source/tools/ToolUnitTests/threadtestwin.d \
./lib/pin2.14/source/tools/ToolUnitTests/tool_fetch_app.d \
./lib/pin2.14/source/tools/ToolUnitTests/tstcmpxchg8b.d \
./lib/pin2.14/source/tools/ToolUnitTests/tstcmpxchg8b_with_explicit_ebx.d \
./lib/pin2.14/source/tools/ToolUnitTests/two.d \
./lib/pin2.14/source/tools/ToolUnitTests/waitpidbug.d 


# Each subdirectory must supply rules for building sources it contributes
lib/pin2.14/source/tools/ToolUnitTests/%.o: ../lib/pin2.14/source/tools/ToolUnitTests/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lib/pin2.14/source/tools/ToolUnitTests/%.o: ../lib/pin2.14/source/tools/ToolUnitTests/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lib/pin2.14/source/tools/ToolUnitTests/%.o: ../lib/pin2.14/source/tools/ToolUnitTests/%.asm
	@echo 'Building file: $<'
	@echo 'Invoking: GCC Assembler'
	as  -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


