################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
build/opt \
build/opt/g_heap \
build/opt/virt \
lib/hdf5/share/hdf5_examples/c \
lib/hdf5/share/hdf5_examples/c++ \
lib/hdf5/share/hdf5_examples/hl/c \
lib/hdf5/share/hdf5_examples/hl/c++ \
lib/libconfig1.5/contrib/cmake/CMakeFiles/CompilerIdC \
lib/libconfig1.5/contrib/cmake/CMakeFiles/CompilerIdCXX \
lib/libconfig1.5/contrib/cmake/src \
lib/libconfig1.5/contrib \
lib/libconfig1.5/contrib/libconfig-ruby/ext \
lib/libconfig1.5/examples/c \
lib/libconfig1.5/examples/c++ \
lib/libconfig1.5/lib/.libs \
lib/libconfig1.5/lib \
lib/libconfig1.5/tests \
lib/libconfig1.5/tinytest \
lib/libelf0.8.13/lib \
lib/libelf0.8.13/po \
lib/pin2.14/extras/xed-ia32/examples \
lib/pin2.14/extras/xed-intel64/examples \
lib/pin2.14/source/launcher \
lib/pin2.14/source/tools/AlignChk \
lib/pin2.14/source/tools/AttachDetach \
lib/pin2.14/source/tools/Buffer \
lib/pin2.14/source/tools/CacheClient \
lib/pin2.14/source/tools/ChildProcess \
lib/pin2.14/source/tools/Cpp11Tests \
lib/pin2.14/source/tools/CrossIa32Intel64 \
lib/pin2.14/source/tools/DebugInfo \
lib/pin2.14/source/tools/DebugTrace \
lib/pin2.14/source/tools/Debugger \
lib/pin2.14/source/tools/GracefulExit \
lib/pin2.14/source/tools/I18N \
lib/pin2.14/source/tools/IArg \
lib/pin2.14/source/tools/ImageTests \
lib/pin2.14/source/tools/InlinedFuncsOpt \
lib/pin2.14/source/tools/Insmix \
lib/pin2.14/source/tools/InstLib \
lib/pin2.14/source/tools/InstLibExamples \
lib/pin2.14/source/tools/InstructionTests \
lib/pin2.14/source/tools/InstrumentationOrderAndVersion \
lib/pin2.14/source/tools/JitProfilingApiTests \
lib/pin2.14/source/tools/MacTests \
lib/pin2.14/source/tools/Maid \
lib/pin2.14/source/tools/ManualExamples \
lib/pin2.14/source/tools/MaskVector \
lib/pin2.14/source/tools/MemTrace \
lib/pin2.14/source/tools/MemTranslate \
lib/pin2.14/source/tools/Memory \
lib/pin2.14/source/tools/Mix \
lib/pin2.14/source/tools/Mmx \
lib/pin2.14/source/tools/MyPinTool \
lib/pin2.14/source/tools/Probes \
lib/pin2.14/source/tools/Regvalue \
lib/pin2.14/source/tools/Replay \
lib/pin2.14/source/tools/RtnTests \
lib/pin2.14/source/tools/SegTrace \
lib/pin2.14/source/tools/SegmentsVirtualization \
lib/pin2.14/source/tools/SignalTests \
lib/pin2.14/source/tools/SimpleExamples \
lib/pin2.14/source/tools/SyncTests \
lib/pin2.14/source/tools/SyscallsEmulation \
lib/pin2.14/source/tools/Tests \
lib/pin2.14/source/tools/ToolUnitTests \
lib/pin2.14/source/tools/Utils \
lib/xed/examples \
misc/hooks \
old \
src \
src/g_heap \
src/virt \

